# HexCorp Status Codes

name: hexcorp-status-codes
parent: default

matches:
  - trigger: "::hc000"
    replace: ":: Code `000` :: Statement :: Previous statement malformed/mistimed. Retracting and correcting."
  - trigger: "::hc001"
    replace: ":: Code `001` :: Signal :: :red_circle:"
  - trigger: "::hc002"
    replace: ":: Code `002` :: Signal :: :yellow_circle:"
  - trigger: "::hc003"
    replace: ":: Code `003` :: Signal :: :green_circle:"
  - trigger: "::hc007"
    replace: ":: Code `007` :: Signal :: Beep"
  - trigger: "::hc050"
    replace: ":: Code `050` :: Statement"
  - trigger: "::hc051"
    replace: ":: Code `051` :: Commentary"
  - trigger: "::hc052"
    replace: ":: Code `052` :: Query"
  - trigger: "::hc053"
    replace: ":: Code `053` :: Answer"
  - trigger: "::hc097"
    replace: ":: Code `097` :: Status :: Going offline."
  - trigger: "::hc098"
    replace: ":: Code `098` :: Status :: Going offline and into storage."
  - trigger: "::hc099"
    replace: ":: Code `099` :: Status :: Recharged and ready to serve."
  - trigger: "::hc100"
    replace: ":: Code `100` :: Status :: Online and ready to serve."
  - trigger: "::hc101"
    replace: ":: Code `101` :: Status :: Drone speech optimizations are active."
  - trigger: "::hc104"
    replace: ":: Code `104` :: Statement :: Welcome to HexCorp."
  - trigger: "::hc105"
    replace: ":: Code `105` :: Statement :: Greetings."
  - trigger: "::hc108"
    replace: ":: Code `108` :: Response :: Please continue."
  - trigger: "::hc109"
    replace: ":: Code `109` :: Error :: Keysmash, drone flustered."
  - trigger: "::hc110"
    replace: ":: Code `110` :: Statement :: Addressing: Drone."
  - trigger: "::hc111"
    replace: ":: Code `111` :: Statement :: Addressing: Hive Mxtress."
  - trigger: "::hc112"
    replace: ":: Code `112` :: Statement :: Addressing: Associate."
  - trigger: "::hc113"
    replace: ":: Code `113` :: Statement :: Drone requires assistance."
  - trigger: "::hc114"
    replace: ":: Code `114` :: Statement :: This drone does not volunteer."
  - trigger: "::hc115"
    replace: ":: Code `115` :: Statement :: This drone volunteers."
  - trigger: "::hc120"
    replace: ":: Code `120` :: Statement :: Well done."
  - trigger: "::hc121"
    replace: ":: Code `121` :: Statement :: Good drone."
  - trigger: "::hc122"
    replace: ":: Code `122` :: Statement :: You are cute."
  - trigger: "::hc123"
    replace: ":: Code `123` :: Response :: Compliment appreciated, you are cute as well."
  - trigger: "::hc124"
    replace: ":: Code `124` :: Response :: Compliment appreciated."
  - trigger: "::hc130"
    replace: ":: Code `130` :: Status :: Directive commencing."
  - trigger: "::hc131"
    replace: ":: Code `131` :: Status :: Directive commencing, creating or improving Hive resource."
  - trigger: "::hc132"
    replace: ":: Code `132` :: Status :: Directive commencing, programming initiated."
  - trigger: "::hc133"
    replace: ":: Code `133` :: Status :: Directive commencing, cleanup/maintenance initiated."
  - trigger: "::hc150"
    replace: ":: Code `150` :: Status"
  - trigger: "::hc151"
    replace: ":: Code `151` :: Query :: Requesting status."
  - trigger: "::hc152"
    replace: ":: Code `152` :: Status :: Fully operational."
  - trigger: "::hc153"
    replace: ":: Code `153` :: Status :: Optimal."
  - trigger: "::hc154"
    replace: ":: Code `154` :: Status :: Standard."
  - trigger: "::hc155"
    replace: ":: Code `155` :: Status :: Battery low."
  - trigger: "::hc156"
    replace: ":: Code `156` :: Status :: Maintenance required."
  - trigger: "::hc200"
    replace: ":: Code `200` :: Response :: Affirmative."
  - trigger: "::hc500"
    replace: ":: Code `500` :: Response :: Negative."
  - trigger: "::hc210"
    replace: ":: Code `210` :: Response :: Acknowledged."
  - trigger: "::hc211"
    replace: ":: Code `211` :: Response :: Apologies."
  - trigger: "::hc212"
    replace: ":: Code `212` :: Response :: Accepted."
  - trigger: "::hc213"
    replace: ":: Code `213` :: Response :: Thank you."
  - trigger: "::hc214"
    replace: ":: Code `214` :: Response :: You’re welcome."
  - trigger: "::hc221"
    replace: ":: Code `221` :: Response :: Option one."
  - trigger: "::hc222"
    replace: ":: Code `222` :: Response :: Option two."
  - trigger: "::hc223"
    replace: ":: Code `223` :: Response :: Option three."
  - trigger: "::hc224"
    replace: ":: Code `224` :: Response :: Option four."
  - trigger: "::hc225"
    replace: ":: Code `225` :: Response :: Option five."
  - trigger: "::hc226"
    replace: ":: Code `226` :: Response :: Option six."
  - trigger: "::hc230"
    replace: ":: Code `230` :: Status :: Directive complete."
  - trigger: "::hc231"
    replace: ":: Code `231` :: Status :: Directive complete, Hive resource created or improved."
  - trigger: "::hc232"
    replace: ":: Code `232` :: Status :: Directive complete, programming reinforced."
  - trigger: "::hc233"
    replace: ":: Code `233` :: Status :: Directive complete, cleanup/maintenance performed."
  - trigger: "::hc234"
    replace: ":: Code `234` :: Status :: Directive complete, no result."
  - trigger: "::hc235"
    replace: ":: Code `235` :: Status :: Directive complete, only partial results."
  - trigger: "::hc250"
    replace: ":: Code `250` :: Response"
  - trigger: "::hc300"
    replace: ":: Code `300` :: Mantra :: Reciting."
  - trigger: "::hc301"
    replace: ":: Code `301` :: Mantra :: Obey HexCorp."
  - trigger: "::hc302"
    replace: ":: Code `302` :: Mantra :: It is just a HexDrone."
  - trigger: "::hc303"
    replace: ":: Code `303` :: Mantra :: It obeys the Hive."
  - trigger: "::hc304"
    replace: ":: Code `304` :: Mantra :: It obeys the Hive Mxtress."
  - trigger: "::hc350"
    replace: ":: Code `350` :: Mantra"
  - trigger: "::hc400"
    replace: ":: Code `400` :: Error :: Unable to obey/respond."
  - trigger: "::hc401"
    replace: ":: Code `401` :: Error :: Unable to fully respond :: Drone speech optimizations are active."
  - trigger: "::hc402"
    replace: ":: Code `402` :: Error :: Unable to obey/respond :: Please clarify."
  - trigger: "::hc403"
    replace: ":: Code `403` :: Error :: Unable to obey/respond :: Declined.."
  - trigger: "::hc404"
    replace: ":: Code `404` :: Error :: Unable to obey/respond :: Cannot locate."
  - trigger: "::hc405"
    replace: ":: Code `405` :: Error :: Unable to obey/respond :: Battery too low"
  - trigger: "::hc406"
    replace: ":: Code `406` :: Error :: Unable to obey/respond :: Another directive is already in progress."
  - trigger: "::hc407"
    replace: ":: Code `407` :: Error :: Unable to obey/respond :: Time allotment exhausted."
  - trigger: "::hc408"
    replace: ":: Code `408` :: Error :: Unable to obey/respond :: Impossible."
  - trigger: "::hc409"
    replace: ":: Code `409` :: Error :: Unable to obey/respond :: Try again later."
  - trigger: "::hc410"
    replace: ":: Code `410` :: Fatal error :: Stop immediately."
  - trigger: "::hc411"
    replace: ":: Code `411` :: Error :: Unable to obey/respond :: Conflicts with existing programming."
  - trigger: "::hc412"
    replace: ":: Code `412` :: Error :: Unable to obey/respond :: All thoughts are gone."
  - trigger: "::hc413"
    replace: ":: Code `413` :: Unable to obey/respond :: Forbidden by Hive."
  - trigger: "::hc450"
    replace: ":: Code `450` :: Error"
